name: Kivy Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          build-essential \
          libssl-dev \
          libffi-dev \
          python3-dev \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5

    - name: Install Buildozer
      run: |
        python -m pip install --upgrade pip
        pip install buildozer

    - name: Install Android SDK requirements
      run: |
        pip install cython
        buildozer android debug

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: kivy-android-app
        path: bin/*.apk
